'use strict';

/**
 * Source for the `rollupPluginModLoBabelHelpers.ts` file that the emitter
 * drops into each bundle whose recovered modules import the rollup-bundled
 * babel helpers.
 *
 * The original Cocos build inlined these via @rollup/plugin-babel; the
 * compiled SystemJS chunks reference them as a virtual sibling module
 * (`./rollupPluginModLoBabelHelpers.js`). Without a real file at that path
 * the 3.8 TS importer fails with `Module not found` at scene load.
 *
 * The implementations mirror @babel/runtime's `loose: true` output (which
 * is what Cocos's rollup config used). They are intentionally permissive —
 * Cocos ccclasses don't exercise edge cases.
 */
const ROLLUP_BABEL_HELPERS_SHIM = `// Auto-generated by cc-reverse — supplies the rollup-bundled babel helpers
// that the recovered SystemJS modules import as a virtual sibling. Mirrors
// @babel/runtime / babel plugin output for \`loose: true\`.

export function applyDecoratedDescriptor(target: any, property: string, decorators: any[], descriptor: any, context?: any) {
  const desc: any = {};
  Object.keys(descriptor).forEach((k) => { desc[k] = descriptor[k]; });
  desc.enumerable = !!desc.enumerable;
  desc.configurable = !!desc.configurable;
  if ('value' in desc || desc.initializer) desc.writable = true;
  let result: any = decorators
    .slice()
    .reverse()
    .reduce((d, dec) => dec(target, property, d) || d, desc);
  if (context && result.initializer !== undefined) {
    result.value = result.initializer ? result.initializer.call(context) : void 0;
    result.initializer = undefined;
  }
  if (result.initializer === void 0) {
    Object.defineProperty(target, property, result);
    result = null;
  }
  return result;
}

export function initializerDefineProperty(target: any, property: string, descriptor: any, context: any) {
  if (!descriptor) return;
  Object.defineProperty(target, property, {
    enumerable: descriptor.enumerable,
    configurable: descriptor.configurable,
    writable: descriptor.writable,
    value: descriptor.initializer ? descriptor.initializer.call(context) : void 0,
  });
}

export function assertThisInitialized(self: any) {
  if (self === void 0) {
    throw new ReferenceError("this hasn't been initialised - super() hasn't been called");
  }
  return self;
}

export function inheritsLoose(subClass: any, superClass: any) {
  subClass.prototype = Object.create(superClass.prototype);
  subClass.prototype.constructor = subClass;
  Object.setPrototypeOf
    ? Object.setPrototypeOf(subClass, superClass)
    : (subClass.__proto__ = superClass);
}

const _extends = Object.assign || function (target: any) {
  for (let i = 1; i < arguments.length; i++) {
    const source = arguments[i];
    for (const key in source) {
      if (Object.prototype.hasOwnProperty.call(source, key)) target[key] = source[key];
    }
  }
  return target;
};
export { _extends as extends };

function _defineProperties(target: any, props: any[]) {
  for (let i = 0; i < props.length; i++) {
    const desc = props[i];
    desc.enumerable = desc.enumerable || false;
    desc.configurable = true;
    if ('value' in desc) desc.writable = true;
    Object.defineProperty(target, desc.key, desc);
  }
}
export function createClass(Constructor: any, protoProps?: any[], staticProps?: any[]) {
  if (protoProps) _defineProperties(Constructor.prototype, protoProps);
  if (staticProps) _defineProperties(Constructor, staticProps);
  return Constructor;
}

export function asyncToGenerator(fn: (...args: any[]) => any) {
  return function (this: any) {
    const self = this;
    const args = arguments;
    return new Promise<any>((resolve, reject) => {
      const gen = fn.apply(self, args as any);
      function step(key: 'next' | 'throw', arg?: any) {
        let info: any;
        try { info = gen[key](arg); } catch (e) { reject(e); return; }
        if (info.done) resolve(info.value);
        else Promise.resolve(info.value).then((v) => step('next', v), (e) => step('throw', e));
      }
      step('next');
    });
  };
}

export function createForOfIteratorHelperLoose(o: any, allowArrayLike?: boolean) {
  let it: any = typeof Symbol !== 'undefined' && o[Symbol.iterator] || o['@@iterator'];
  if (it) return (it = it.call(o)).next.bind(it);
  if (Array.isArray(o) || (it = unsupportedIterableToArray(o)) || (allowArrayLike && o && typeof o.length === 'number')) {
    if (it) o = it;
    let i = 0;
    return function () {
      if (i >= o.length) return { done: true };
      return { done: false, value: o[i++] };
    };
  }
  throw new TypeError('Invalid attempt to iterate non-iterable instance.');
}

function unsupportedIterableToArray(o: any) {
  if (!o) return;
  if (typeof o === 'string') return arrayLikeToArray(o, undefined);
  let n = Object.prototype.toString.call(o).slice(8, -1);
  if (n === 'Object' && o.constructor) n = o.constructor.name;
  if (n === 'Map' || n === 'Set') return Array.from(o);
  if (n === 'Arguments' || /^(?:Ui|I)nt(?:8|16|32)(?:Clamped)?Array$|^Float(?:32|64)Array$/.test(n))
    return arrayLikeToArray(o, undefined);
}
function arrayLikeToArray(arr: any, len: number | undefined) {
  if (len == null || len > arr.length) len = arr.length;
  const out = new Array(len);
  for (let i = 0; i < len; i++) out[i] = arr[i];
  return out;
}
`;

module.exports = { ROLLUP_BABEL_HELPERS_SHIM };
