/*
 * Emit a Cocos Creator-compatible project skeleton so the output directory
 * opens as a project in the editor.
 *
 * Supports both 2.4.x (bundle-style) and 3.x outputs. Most editor metadata
 * (library/, local/, temp/) is rebuilt on first open, so we only need to
 * seed the parts the editor *reads* up front: project.json + settings/.
 */
const fs = require('fs');
const path = require('path');
const { promisify } = require('util');
const { uuidUtils } = require('../../utils/uuidUtils');

const mkdir = promisify(fs.mkdir);
const writeFile = promisify(fs.writeFile);

/**
 * Write a Cocos Creator 2.4.x project skeleton (the "bundle-style" variant —
 * what the daoshi test project used).
 *
 * @param {string} outputPath     recovery output root
 * @param {object} opts
 * @param {string} opts.projectName
 * @param {string} [opts.cocosVersion='2.4.14']
 * @param {object} [opts.settings]  parsed window._CCSettings contents
 * @param {object[]} [opts.bundles] recovered bundle summaries
 */
async function writeCocos2xProject(outputPath, opts) {
  const {
    projectName = 'recovered-project',
    cocosVersion = '2.4.14',
    settings = {},
    bundles = [],
  } = opts;

  const projectId = uuidUtils.generateUuid();

  // project.json — the editor's entry point.
  const projectJson = {
    engine: 'cocos2d-html5',
    packages: 'packages',
    name: projectName,
    id: projectId,
    version: cocosVersion,
    creator: { version: cocosVersion },
  };
  await writeFile(
    path.join(outputPath, 'project.json'),
    JSON.stringify(projectJson, null, 2),
  );

  // package.json — npm descriptor for Creator's module system.
  const pkgJson = {
    name: projectName,
    version: '1.0.0',
    description: 'Recovered by cc-reverse',
    dependencies: {},
  };
  await writeFile(
    path.join(outputPath, 'package.json'),
    JSON.stringify(pkgJson, null, 2),
  );

  // settings/ — holds builder presets + project configuration.
  const settingsDir = path.join(outputPath, 'settings');
  await mkdir(settingsDir, { recursive: true });

  // settings/project.json — creator project settings (physics, groups, etc.)
  const groupList = settings.groupList || ['default'];
  const collisionMatrix = settings.collisionMatrix || [[true]];
  const designResolution = settings.designResolution || { width: 1280, height: 720, policy: 4 };
  const projectSettings = {
    'facebook': { 'appID': '', 'audience': { 'enable': false }, 'enable': false, 'live': { 'enable': false } },
    'start-scene': settings.launchScene || 'current',
    'design-resolution-width': designResolution.width,
    'design-resolution-height': designResolution.height,
    'fit-width': false,
    'fit-height': false,
    'group-list': groupList,
    'collision-matrix': collisionMatrix,
    'excluded-modules': [],
    'last-module-event-record-time': 0,
    'assets-sort-type': 'name',
    'use-project-simulator-setting': false,
    'simulator-orientation': false,
    'use-customize-simulator': false,
    'simulator-resolution': { width: 960, height: 640 },
    'package-name': 'org.cocos2d.' + projectName.toLowerCase().replace(/[^a-z0-9]/g, ''),
    'migrate-history': [],
  };
  await writeFile(
    path.join(settingsDir, 'project.json'),
    JSON.stringify(projectSettings, null, 2),
  );

  // settings/builder.json — build panel preferences. Seed the bundles we
  // recovered so the editor shows them as configured asset bundles.
  const builderSettings = {
    actualPlatform: 'wechatgame',
    android: { packageName: projectSettings['package-name'] },
    'android-instant': { packageName: projectSettings['package-name'] },
    appBundle: false,
    apkUrl: '',
    buildPath: 'build',
    debug: true,
    inlineSpriteFrames: false,
    inlineSpriteFrames_native: true,
    md5Cache: false,
    mergeStartScene: false,
    optimizeHotUpdate: false,
    platform: 'wechatgame',
    previewHeight: 640,
    previewWidth: 960,
    scenes: extractSceneUrls(settings, bundles),
    sourceMaps: false,
    startScene: settings.launchScene || '',
    title: projectName,
    webOrientation: 'auto',
  };
  await writeFile(
    path.join(settingsDir, 'builder.json'),
    JSON.stringify(builderSettings, null, 2),
  );

  // packages/ — editor plugins dir, kept empty.
  await mkdir(path.join(outputPath, 'packages'), { recursive: true });

  // creator.d.ts — type hints. Keep minimal; editor regenerates from engine.
  await writeFile(
    path.join(outputPath, 'creator.d.ts'),
    '// Type definitions are regenerated by the editor on first open.\n',
  );

  // jsconfig.json — lets VS Code resolve cc.* types.
  const jsconfig = {
    compilerOptions: {
      module: 'commonjs',
      target: 'es2017',
      experimentalDecorators: true,
      allowSyntheticDefaultImports: true,
    },
    exclude: ['node_modules', 'library', 'local', 'temp', 'build', 'settings'],
  };
  await writeFile(
    path.join(outputPath, 'jsconfig.json'),
    JSON.stringify(jsconfig, null, 2),
  );

  // .gitignore — standard Cocos Creator ignores.
  const gitignore = [
    'library/', 'local/', 'temp/', 'build/',
    'node_modules/', '*.log', '.DS_Store',
  ].join('\n') + '\n';
  await writeFile(path.join(outputPath, '.gitignore'), gitignore);

  return { projectJson, builderSettings };
}

function extractSceneUrls(settings, bundles) {
  const urls = [];
  if (Array.isArray(settings.scenes)) {
    for (const s of settings.scenes) {
      if (s && s.url) urls.push({ url: s.url, inline: false });
    }
  }
  // Also include scenes we recovered from bundle configs.
  for (const b of bundles) {
    if (!b || !b.scenes) continue;
    for (const [name] of Object.entries(b.scenes)) {
      const url = name.startsWith('db://') ? name : `db://assets/${b.name}/scene/${name}.fire`;
      if (!urls.some(u => u.url === url)) urls.push({ url, inline: false });
    }
  }
  return urls;
}

module.exports = { writeCocos2xProject };
